// Upstream curriculum introduced after the local 00-11 learning notes were built.
// Keep this metadata separate so the deeply customized early lessons remain stable.

const level = (id, title, file, category, difficulty, tags, summary, concepts, quiz, handsOn, formula) => ({
  id,
  title,
  file,
  category,
  difficulty,
  tags,
  summary,
  concepts,
  quiz,
  handsOn,
  formula
});

module.exports = [
  level("12", "Gradient Accumulation", "12_Gradient_Accumulation.ipynb", "training", "Medium",
    ["Gradient Accumulation", "Micro-batch", "Memory"],
    "把一个大 batch 拆成多个 micro-batch 累积梯度，用更多计算步骤换更低峰值显存。",
    ["累积期间不能提前 optimizer.step。", "每个 micro-batch 的 loss 要按累积步数缩放。", "最后一次统一更新，才能近似等价于大 batch。"],
    { question: "梯度累积时为什么常把每个 micro-batch loss 除以累积步数？", options: ["让累计梯度与大 batch 的平均 loss 对齐", "让模型参数变少", "避免创建优化器"], answer: 0, explain: "缩放后再累计，整体梯度尺度才与对完整 batch 求平均一致。" },
    ["按 micro_batch_size 切分输入和标签。", "缩放 loss 后逐次 backward。", "循环结束再 step，并核对累计 loss。"],
    "effective_batch = micro_batch × accumulation_steps"),

  level("13", "End-to-End Fine-Tuning Experiment", "13_End_to_End_Fine_Tuning_Experiment.ipynb", "training", "Medium",
    ["SFT", "Training Loop", "Loss Mask"],
    "把样本构造、next-token loss、梯度累积和参数更新串成一个最小但完整的微调闭环。",
    ["SFT 样本要区分 prompt 与 response 的监督范围。", "causal LM 使用错一位的 logits 和 labels。", "训练闭环包含 zero_grad、backward、step 与指标记录。"],
    { question: "SFT 中为什么常把 prompt token 的 label 设为 ignore_index？", options: ["只让 response 部分贡献监督信号", "缩短 tokenizer 词表", "让模型跳过前向传播"], answer: 0, explain: "忽略 prompt label 后，loss 聚焦于回答部分的 next-token 预测。" },
    ["构造 prompt/response 与 loss mask。", "对齐 shifted logits 和 labels。", "跑通至少一次完整参数更新。"],
    "input → masked next-token loss → backward → optimizer.step"),

  level("14", "RLHF PPO Memory", "14_RLHF_PPO_Memory.ipynb", "training", "Hard",
    ["RLHF", "PPO", "Clipped Objective"],
    "从新旧策略概率比率出发，实现带 clip 护栏的 PPO actor loss。",
    ["ratio 等于 exp(new_logprob-old_logprob)。", "advantage 决定提高还是降低动作概率。", "clip 限制单次策略更新幅度。"],
    { question: "PPO clip 的主要作用是什么？", options: ["限制新策略偏离旧策略过远", "删除 reward model", "把概率变成整数"], answer: 0, explain: "截断概率比率可以抑制过大的策略更新。" },
    ["计算概率比率。", "构造 raw 与 clipped surrogate。", "取较保守目标并加负号得到 loss。"],
    "loss = -mean(min(ratio·A, clip(ratio)·A))"),

  level("15", "DPO Loss Tutorial", "15_DPO_Loss_Tutorial.ipynb", "training", "Hard",
    ["DPO", "Preference", "Alignment"],
    "用 chosen/rejected 偏好对和 reference policy，直接构造偏好优化损失。",
    ["DPO 比较 chosen 与 rejected 的相对 log probability。", "reference policy 提供偏离基准。", "beta 控制偏好优化强度。"],
    { question: "DPO 训练数据的核心形式是什么？", options: ["chosen/rejected 偏好对", "无标签随机 token", "图像边界框"], answer: 0, explain: "DPO 直接从成对偏好中学习回答排序。" },
    ["计算 policy 的 chosen/rejected 差。", "减去 reference 的对应差。", "用 log-sigmoid 得到 DPO loss。"],
    "loss = -log σ(β·(policy_margin-reference_margin))"),

  level("16", "GRPO Loss Tutorial", "16_GRPO_Loss_Tutorial.ipynb", "training", "Medium-Hard",
    ["GRPO", "Group Advantage", "Alignment"],
    "在组内标准化奖励得到相对优势，再用 clipped surrogate 更新策略。",
    ["同组样本的奖励共同定义相对优势。", "组内标准化减少奖励尺度差异。", "GRPO 可复用 PPO 式 ratio 与 clip，但不依赖显式 Critic。"],
    { question: "GRPO 的相对优势主要从哪里得到？", options: ["同组样本奖励的归一化比较", "token id 的大小", "模型层数"], answer: 0, explain: "GRPO 用组内均值和标准差把绝对奖励转成相对优势。" },
    ["按 group_ids 聚合奖励。", "计算组内归一化 advantage。", "构造 clipped loss 并检查数值稳定性。"],
    "A_i = (r_i-mean(r_group))/(std(r_group)+eps)"),

  level("17", "Autograd Basics", "17_Autograd_Basics.ipynb", "architecture", "Medium",
    ["Autograd", "Attention Backward", "Chain Rule"],
    "沿 O=softmax(QKᵀ)V 的计算图逆向推导 dV、dP、dS、dQ 与 dK。",
    ["反向传播按前向计算图的逆序进行。", "softmax 同一行的元素梯度相互耦合。", "矩阵乘法反传必须持续核对转置和 shape。"],
    { question: "Attention backward 中为什么不能把 softmax 当作逐元素独立函数？", options: ["同一行概率共享归一化分母", "softmax 没有梯度", "Q 和 K 必须是整数"], answer: 0, explain: "一个 logit 变化会影响同一行所有 softmax 概率。" },
    ["从 O=PV 推导 dV 与 dP。", "实现一行 softmax backward。", "从 S=QKᵀ·scale 推导 dQ 与 dK。"],
    "dS = P ⊙ (dP-sum(dP⊙P))"),

  level("18", "Activation and Loss Backward", "18_Activation_and_Loss_Backward.ipynb", "foundation", "Medium",
    ["ReLU Backward", "Cross Entropy", "Gradient Check"],
    "从 ReLU 门控和交叉熵梯度入手，把常用激活与损失的反向传播写成可验证代码。",
    ["ReLU backward 用 x>0 的 mask 控制梯度通路。", "softmax-cross-entropy 梯度可化简为 probability-one_hot。", "手写梯度应与 autograd 做数值对比。"],
    { question: "ReLU 输入小于等于 0 的位置，反向梯度通常是多少？", options: ["0", "1", "等于输入"], answer: 0, explain: "这些位置在前向被截断，局部导数为 0。" },
    ["构造 ReLU backward mask。", "推导并实现交叉熵梯度。", "与 PyTorch autograd 的结果比较。"],
    "dReLU/dx = 1[x>0]; dCE/dlogits = p-one_hot(y)"),

  level("19", "Activation Checkpointing and Activation Offload", "19_Activation_Checkpointing_and_Activation_Offload.ipynb", "training", "Medium",
    ["Checkpointing", "Offload", "Memory"],
    "用反向重计算和激活卸载理解训练中的计算、显存与传输三方权衡。",
    ["checkpoint 少存激活、反向时重算前向。", "offload 把激活转移到 CPU 或其他存储。", "两者都节省 GPU 显存，但成本分别是计算或传输。"],
    { question: "Activation checkpointing 主要用什么换显存？", options: ["额外重计算", "更大的词表", "更少训练数据"], answer: 0, explain: "反向时重算部分前向，因此少保存中间激活。" },
    ["用 checkpoint 包裹 Transformer block。", "区分重计算与 offload 的成本。", "设计不同 checkpoint 粒度的对比实验。"],
    "less activation memory ↔ recompute / transfer overhead"),

  level("20", "FlashAttention Sim", "20_FlashAttention_Sim.ipynb", "inference", "Hard",
    ["FlashAttention", "Online Softmax", "Tiling"],
    "用分块 QKV 计算和在线 softmax，理解 FlashAttention 如何降低 HBM 读写。",
    ["FlashAttention 不改变精确 attention 的数学结果。", "分块避免物化完整 N×N 注意力矩阵。", "在线 softmax 维护行最大值和归一化因子。"],
    { question: "FlashAttention 的核心优化对象是什么？", options: ["HBM 读写与中间矩阵", "softmax 的定义", "tokenizer 速度"], answer: 0, explain: "它通过 IO-aware 的分块计算减少昂贵的数据搬运。" },
    ["初始化在线 softmax 状态。", "逐块更新 m、l 与输出。", "和普通 attention 做数值比较。"],
    "online softmax keeps per-row m and l across blocks"),

  level("21", "Decoding Strategies", "21_Decoding_Strategies.ipynb", "inference", "Medium",
    ["Temperature", "Top-K", "Top-P"],
    "比较温度缩放、Top-K 和 Top-P 如何改变候选集合与生成多样性。",
    ["temperature 控制概率分布尖锐程度。", "Top-K 只保留固定数量候选。", "Top-P 保留累计概率达到阈值的动态候选集。"],
    { question: "提高 temperature 通常会怎样影响输出？", options: ["增加随机性和多样性", "变成完全 greedy", "删除低编号 token"], answer: 0, explain: "较高温度会压平概率分布。" },
    ["实现温度缩放。", "实现 Top-K 截断。", "实现 Top-P 排序、累计与散射还原。"],
    "p(token)=softmax(logits/temperature)"),

  level("22", "vLLM PagedAttention", "22_vLLM_PagedAttention.ipynb", "inference", "Hard",
    ["PagedAttention", "KV Cache", "Block Table"],
    "把 KV Cache 切成物理块并用 block table 映射，减少服务场景中的内存碎片。",
    ["逻辑 token 块不必连续映射到物理内存。", "Prefill 会一次申请多个 block。", "Decode 只在跨过 block 边界时申请新块。"],
    { question: "PagedAttention 借鉴了哪种系统思想？", options: ["虚拟内存分页", "卷积池化", "数据库排序"], answer: 0, explain: "逻辑块通过表映射到离散物理块。" },
    ["初始化物理 KV block 池。", "实现 Prefill/Decode 分配。", "按 block table 拼装请求 KV。"],
    "logical block → block table → physical KV block"),

  level("23", "Speculative Decoding", "23_Speculative_Decoding.ipynb", "inference", "Hard",
    ["Draft Model", "Verification", "Acceptance"],
    "让小模型提出多个候选，再由目标模型并行验证，在保持目标分布的前提下加速生成。",
    ["draft model 只负责快速提议。", "target model 决定接受或拒绝。", "首次拒绝后停止验证后续草稿 token。"],
    { question: "draft model 的职责是什么？", options: ["快速提出候选 token", "永久替代 target model", "只做分词"], answer: 0, explain: "最终分布仍由 target model 的验证规则保证。" },
    ["逐 token 读取 draft/target 概率。", "实现 min(1,p/q) 接受规则。", "在拒绝时终止后续验证。"],
    "acceptance α(x)=min(1,p_target(x)/p_draft(x))"),

  level("24", "SGLang RadixAttention", "24_SGLang_RadixAttention.ipynb", "inference", "Hard",
    ["RadixAttention", "Prefix Cache", "KV Reuse"],
    "用基数树匹配共享 prompt 前缀，复用已经计算过的 KV Cache。",
    ["系统提示词等公共前缀会被大量请求重复使用。", "radix tree 用路径表达 token 前缀。", "最长前缀命中决定可复用与待重算部分。"],
    { question: "RadixAttention 主要消除什么重复？", options: ["共享前缀的 Prefill/KV 计算", "优化器更新", "词表训练"], answer: 0, explain: "命中缓存前缀后，只需计算未命中的后缀。" },
    ["实现两条 token 路径的最长公共前缀。", "遍历缓存寻找最长命中。", "拆分 reusable prefix 与 suffix。"],
    "request = cached_prefix + suffix_to_compute"),

  level("25", "Quantization W8A16", "25_Quantization_W8A16.ipynb", "inference", "Medium",
    ["Quantization", "W8A16", "Absmax"],
    "把浮点权重量化到 INT8，再反量化参与 W8A16 线性计算。",
    ["W8A16 表示权重 8-bit、激活 16-bit。", "absmax 决定对称量化 scale。", "round 与 clamp 把浮点值映射到 INT8 范围。"],
    { question: "W8A16 中 W8 表示什么？", options: ["权重使用 8-bit", "窗口长度为 8", "每层 8 个 head"], answer: 0, explain: "W 表示 weight，8 表示位宽。" },
    ["计算 absmax 与 scale。", "量化并 clamp 到 INT8。", "反量化后比较线性层误差。"],
    "q=clamp(round(x·127/absmax),-128,127)"),

  level("26", "QLoRA and 4bit Quantization", "26_QLoRA_and_4bit_Quantization.ipynb", "training", "Hard",
    ["QLoRA", "NF4", "PEFT"],
    "冻结低精度基座权重，只训练高精度 LoRA 旁路，模拟 QLoRA 的低显存微调。",
    ["NF4 用查表索引存储量化权重。", "前向时先反量化基础分支。", "只有 LoRA A/B 参数参与训练。"],
    { question: "QLoRA 中通常更新哪部分参数？", options: ["LoRA adapter", "全部 4-bit base weights", "tokenizer"], answer: 0, explain: "量化基座被冻结，可训练增量来自 LoRA。" },
    ["用 NF4 table 反量化基础权重。", "计算 base 与 LoRA 两条分支。", "检查 base 冻结、LoRA 有梯度。"],
    "output=linear(x,dequant(W_nf4))+LoRA(x)"),

  level("27", "ZeRO Optimizer Sim", "27_ZeRO_Optimizer_Sim.ipynb", "training", "Hard",
    ["ZeRO", "Optimizer State", "Sharding"],
    "模拟把优化器状态分片到不同设备，理解 ZeRO-1 到 ZeRO-3 的逐级切分。",
    ["普通数据并行会复制参数、梯度和优化器状态。", "ZeRO-1 首先切优化器状态。", "ZeRO-2/3 继续切梯度和参数。"],
    { question: "ZeRO-3 相比 ZeRO-2 进一步切分什么？", options: ["模型参数", "训练样本", "tokenizer"], answer: 0, explain: "ZeRO-3 连参数也按 rank 分片。" },
    ["把参数划分给模拟 GPU。", "初始化局部 optimizer state。", "仅由负责该参数的设备更新。"],
    "ZeRO-1: states; ZeRO-2: +grads; ZeRO-3: +params"),

  level("28", "Pipeline Parallelism MicroBatch", "28_Pipeline_Parallelism_MicroBatch.ipynb", "training", "Hard",
    ["Pipeline Parallelism", "Micro-batch", "Bubble"],
    "构造流水线时间轴并计算空泡比例，理解 micro-batch 如何提升 stage 利用率。",
    ["模型层被切到多个 stage。", "micro-batch 在 stage 间交错流动。", "填充与排空阶段形成 pipeline bubble。"],
    { question: "增加 micro-batch 数通常会怎样影响空泡比例？", options: ["降低", "升高到 1", "完全无关"], answer: 0, explain: "有效计算增多，会摊薄固定的填充与排空开销。" },
    ["生成 stage×time 时间轴。", "标记活跃槽位。", "计算并比较不同 micro-batch 数的 bubble ratio。"],
    "bubble≈(stages-1)/(micro_batches+stages-1)"),

  level("29", "Tensor Parallelism Sim", "29_Tensor_Parallelism_Sim.ipynb", "training", "Hard",
    ["Tensor Parallelism", "All-Gather", "All-Reduce"],
    "分别模拟 Column/Row Parallel Linear，理解切分维度与通信方式的配对。",
    ["Column Parallel 切输出列并拼接局部输出。", "Row Parallel 切输入行并求和局部贡献。", "切分方向决定 All-Gather 或 All-Reduce。"],
    { question: "Row Parallel Linear 如何合并局部输出？", options: ["求和模拟 All-Reduce", "沿 batch 拼接", "Top-K"], answer: 0, explain: "各 rank 算的是同一输出的部分和，需要相加。" },
    ["按列切权重并 concat 输出。", "按行切输入和权重。", "sum 局部结果并与单卡基准比较。"],
    "column: concat(XW_i); row: sum(X_iW_i)"),

  level("30", "LoRA Fine-Tuning Project", "30_LoRA_Fine_Tuning_Project.ipynb", "training", "Project",
    ["LoRA", "Fine-tuning", "Experiment"],
    "把 LoRA 放进可交付微调流程，用训练效果、参数量、显存和速度共同验证收益。",
    ["先冻结 backbone，再插入低秩 A/B 参数。", "项目评价不能只看 loss，还要记录效率指标。", "对比实验必须保持数据和训练设置一致。"],
    { question: "LoRA 项目中最公平的对比方式是什么？", options: ["固定数据与训练设置，对比可训练参数、效果和效率", "每次更换数据集", "只比较文件大小"], answer: 0, explain: "控制变量后，指标差异才可归因于微调方案。" },
    ["验证只有 LoRA 参数可训练。", "跑通训练并记录 loss。", "汇总参数量、耗时和显存结果。"],
    "quality + trainable params + memory + throughput"),

  level("31", "Inference Performance Comparison", "31_Inference_Performance_Comparison.ipynb", "inference", "Project",
    ["Benchmark", "Latency", "Throughput"],
    "建立可重复的推理基准，对比不同实现的延迟、吞吐与数值一致性。",
    ["benchmark 前要 warmup。", "延迟与吞吐需要分开测量。", "优化后仍需检查输出误差或任务质量。"],
    { question: "为什么正式计时前通常要 warmup？", options: ["排除初始化、缓存和编译开销的干扰", "让参数数量变少", "清空输入"], answer: 0, explain: "预热后测量更接近稳定运行状态。" },
    ["固定输入与随机种子。", "执行 warmup 和多轮计时。", "报告 P50/平均延迟、吞吐与误差。"],
    "throughput = processed tokens / elapsed time"),

  level("32", "Training Performance Analysis", "32_Training_Performance_Analysis.ipynb", "training", "Project",
    ["Profiling", "Training", "Memory"],
    "把训练 step 拆成数据、前向、反向和优化器阶段，定位真正的性能与显存瓶颈。",
    ["总 step time 需要按阶段拆分。", "峰值显存应在相同 batch 与模型设置下比较。", "优化前先用 profiler 或计时证据定位瓶颈。"],
    { question: "训练变慢时最先应该做什么？", options: ["分阶段计时或 profiling 定位瓶颈", "盲目减小所有张量", "删除 loss"], answer: 0, explain: "先获得证据，才能判断是数据、计算、同步还是显存问题。" },
    ["记录 data/forward/backward/step 耗时。", "测量峰值显存与吞吐。", "只改变一个因素并复测。"],
    "step_time=data+forward+backward+optimizer(+sync)")
];
